import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import {
  Header,
  Footer,
  TanStackProvider,
  AuthProvider,
} from '@/app/components';

import css from './layout.module.css';
import './globals.css';

//===========================================================================

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//===========================================================================

function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <TanStackProvider>
          <AuthProvider>
            <Header />
            <div className="container">
              <main className={css.main}>
                <div className={css.container}>
                  {children}
                  {modal}
                </div>
              </main>

              <Footer />
            </div>
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}

export default RootLayout;
